export const DAFTAR_VAKSIN_COVID:string[] = ['Sinovac','AstraZeneca','Sinopharm', 'Moderna', 'Pfizer', 'Novavax']
export const DAFTAR_KECAMATAN:string[] = [
  'all',
  'haharu',
  'kahali',
  'kahaungu_eti',
  'kambata_mapambuhang',
  'kambera',
  'kanatang',
  'karera',
  'kota',
  'lewa',
  'lewa_tidahu',
  'mahu',
  'matawai_lapau',
  'ngadungala',
  'nggoa',
  'paberiwa',
  'pahungga_lodu',
  'pandawai',
  'pinu_pahar',
  'rindi',
  'tabundung',
  'umalulu',
  'wula_waijelu'
]
